__version__ = "0.1.2"
__author__  = "Jayensee"
__author_email__ = "jayensee.lol+ratingsystems@gmail.com"
__url__ = "https://jayensee.github.io/"
__description__  = "Rating systems for pairwise comparisons"